/* The following code was generated by JFlex 1.6.1 */

/************************************************************************************************/
/* i-Code CNES is a static code analyzer.                                                       */
/* This software is a free software, under the terms of the Eclipse Public License version 1.0. */ 
/* http://www.eclipse.org/legal/epl-v10.html                                                    */
/************************************************************************************************/ 

/*****************************************************************************/
/* This file is used to generate a rule checker for F77.INST.If rule.  		 */
/* For further information on this, we advise you to refer to RNC manuals.	 */
/* As many comments have been done on the ExampleRule.lex file, this file    */
/* will restrain its comments on modifications.								 */
/*																			 */
/*****************************************************************************/

package fr.cnes.analysis.tools.fortran77.rules;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.List;

import org.eclipse.core.runtime.IPath;

import fr.cnes.analysis.tools.analyzer.exception.JFlexException;
import fr.cnes.analysis.tools.analyzer.datas.AbstractRule;import fr.cnes.analysis.tools.analyzer.datas.Violation;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>lex/F77INSTIf.lex</tt>
 */
public class F77INSTIf extends AbstractRule {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int NAMING = 4;
  public static final int NEW_LINE = 6;
  public static final int LINE = 8;
  public static final int IF = 10;
  public static final int BRAKET = 12;
  public static final int COMA = 14;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7, 7
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\61\1\54\1\55\1\55\1\55\22\0\1\60\1\1\1\50"+
    "\4\0\1\47\1\56\1\57\1\4\5\0\12\51\7\0\1\36\1\32"+
    "\1\3\1\24\1\23\1\5\1\35\1\52\1\11\2\45\1\43\1\37"+
    "\1\7\1\12\1\21\1\45\1\22\1\31\1\10\1\6\5\45\4\0"+
    "\1\46\1\0\1\41\1\34\1\2\1\30\1\27\1\13\1\40\1\53"+
    "\1\17\2\45\1\44\1\42\1\15\1\20\1\25\1\45\1\26\1\33"+
    "\1\16\1\14\5\45\12\0\1\55\u1fa2\0\1\55\1\55\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\10\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\15\5\2\7\1\10\1\11\1\12\1\13\1\14\3\2"+
    "\1\15\2\5\1\16\11\5\2\0\2\2\4\0\3\5"+
    "\1\2\5\5\2\2\2\0\13\5\2\0\12\5\2\0"+
    "\10\5\1\17\2\0\6\5\2\0\2\5\2\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[120];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\u012c\0\u015e"+
    "\0\u0190\0\u0190\0\u0190\0\u0190\0\u0190\0\u01c2\0\u0190\0\u01f4"+
    "\0\u0226\0\u0258\0\u028a\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384"+
    "\0\u03b6\0\u03e8\0\u041a\0\u044c\0\u047e\0\u04b0\0\u0190\0\u0190"+
    "\0\u0190\0\u0190\0\u0190\0\u04e2\0\u0514\0\u0546\0\u0578\0\u05aa"+
    "\0\u05dc\0\u01f4\0\u060e\0\u0640\0\u0672\0\u06a4\0\u06d6\0\u0708"+
    "\0\u073a\0\u076c\0\u079e\0\u047e\0\u04b0\0\u07d0\0\u0802\0\u0834"+
    "\0\u0866\0\u0898\0\u05aa\0\u08ca\0\u08fc\0\u092e\0\u01f4\0\u0960"+
    "\0\u0992\0\u09c4\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe\0\u0af0"+
    "\0\u0b22\0\u0b54\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e\0\u0c80"+
    "\0\u0cb2\0\u0ce4\0\u04e2\0\u0d16\0\u0d48\0\u0d7a\0\u0dac\0\u0dde"+
    "\0\u0e10\0\u0e42\0\u0e74\0\u0ea6\0\u0ed8\0\u0f0a\0\u0f3c\0\u0f6e"+
    "\0\u0fa0\0\u0fd2\0\u1004\0\u1036\0\u1068\0\u109a\0\u10cc\0\u10fe"+
    "\0\u1130\0\u01f4\0\u1162\0\u1194\0\u11c6\0\u11f8\0\u122a\0\u125c"+
    "\0\u128e\0\u12c0\0\u12f2\0\u1324\0\u1356\0\u1388\0\u13ba\0\u13ec";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[120];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\11\4\12\47\11\1\13\1\14\4\11\1\15\1\12"+
    "\52\15\1\13\1\14\5\15\1\12\2\16\1\15\41\16"+
    "\4\15\2\16\1\13\1\14\4\15\1\11\4\12\47\11"+
    "\1\15\1\14\4\11\1\17\1\12\2\20\1\17\1\21"+
    "\3\20\1\22\1\20\1\23\3\20\1\24\1\20\1\25"+
    "\1\20\1\26\1\20\1\27\1\20\1\30\1\20\1\31"+
    "\1\20\1\32\3\20\1\33\2\20\1\34\3\20\1\17"+
    "\1\35\1\36\1\17\2\20\1\37\3\17\3\15\1\12"+
    "\52\15\1\40\1\14\1\41\4\15\1\12\54\15\1\42"+
    "\1\43\3\15\1\12\2\44\1\15\3\44\1\45\5\44"+
    "\1\46\27\44\3\15\1\47\2\44\1\50\1\14\4\15"+
    "\64\0\2\16\1\0\42\16\2\0\3\16\10\0\2\20"+
    "\1\0\42\20\2\0\3\20\10\0\2\20\1\0\1\20"+
    "\1\51\40\20\2\0\3\20\10\0\2\20\1\0\1\52"+
    "\41\20\2\0\3\20\10\0\2\20\1\0\7\20\1\53"+
    "\32\20\2\0\3\20\10\0\2\20\1\0\6\20\1\52"+
    "\33\20\2\0\3\20\10\0\2\20\1\0\15\20\1\54"+
    "\24\20\2\0\3\20\10\0\2\20\1\0\2\20\1\55"+
    "\37\20\2\0\3\20\10\0\2\20\1\0\21\20\1\56"+
    "\20\20\2\0\3\20\10\0\2\20\1\0\10\20\1\57"+
    "\31\20\2\0\3\20\10\0\2\20\1\0\1\20\1\60"+
    "\40\20\2\0\3\20\10\0\2\20\1\0\7\20\1\61"+
    "\32\20\2\0\3\20\10\0\2\20\1\0\5\20\1\62"+
    "\34\20\2\0\3\20\10\0\2\20\1\0\13\20\1\63"+
    "\26\20\2\0\3\20\6\0\47\64\1\15\12\64\50\65"+
    "\1\15\11\65\2\0\2\44\1\0\42\44\2\0\3\44"+
    "\10\0\2\44\1\0\42\44\2\0\1\44\1\66\1\44"+
    "\10\0\2\44\1\0\42\44\2\0\2\44\1\67\10\0"+
    "\1\70\1\71\45\0\1\47\6\0\1\72\2\0\4\12"+
    "\53\0\1\73\3\0\2\20\1\0\2\20\1\74\37\20"+
    "\2\0\3\20\10\0\2\20\1\0\10\20\1\75\31\20"+
    "\2\0\3\20\10\0\2\20\1\0\5\20\1\76\34\20"+
    "\2\0\3\20\10\0\2\20\1\0\17\20\1\77\22\20"+
    "\2\0\3\20\10\0\2\20\1\0\13\20\1\100\26\20"+
    "\2\0\3\20\10\0\2\20\1\0\23\20\1\77\16\20"+
    "\2\0\3\20\10\0\2\20\1\0\25\20\1\101\14\20"+
    "\2\0\3\20\10\0\2\20\1\0\27\20\1\102\12\20"+
    "\2\0\3\20\10\0\2\20\1\0\17\20\1\103\22\20"+
    "\2\0\3\20\10\0\2\20\1\0\23\20\1\104\16\20"+
    "\2\0\3\20\10\0\2\44\1\0\16\44\1\105\23\44"+
    "\2\0\3\44\10\0\2\44\1\0\22\44\1\106\17\44"+
    "\2\0\3\44\26\0\1\107\53\0\1\110\51\0\1\70"+
    "\1\71\54\0\1\72\3\0\1\20\1\111\1\0\42\20"+
    "\2\0\3\20\10\0\1\112\1\20\1\0\42\20\2\0"+
    "\3\20\10\0\1\20\1\113\1\0\30\20\1\114\11\20"+
    "\2\0\3\20\10\0\1\115\1\20\1\0\33\20\1\116"+
    "\6\20\2\0\3\20\10\0\2\20\1\0\15\20\1\117"+
    "\24\20\2\0\3\20\10\0\2\20\1\0\21\20\1\120"+
    "\20\20\2\0\3\20\10\0\2\20\1\0\1\20\1\121"+
    "\40\20\2\0\3\20\10\0\2\20\1\0\7\20\1\122"+
    "\32\20\2\0\3\20\10\0\2\44\1\0\2\44\1\123"+
    "\37\44\2\0\3\44\10\0\2\44\1\0\10\44\1\123"+
    "\31\44\2\0\3\44\23\0\1\124\53\0\1\125\54\0"+
    "\2\20\1\0\3\20\1\126\36\20\2\0\3\20\10\0"+
    "\2\20\1\0\11\20\1\127\30\20\2\0\3\20\10\0"+
    "\2\20\1\0\16\20\1\130\23\20\2\0\3\20\10\0"+
    "\2\20\1\0\15\20\1\131\24\20\2\0\3\20\10\0"+
    "\2\20\1\0\22\20\1\132\17\20\2\0\3\20\10\0"+
    "\2\20\1\0\21\20\1\133\20\20\2\0\3\20\10\0"+
    "\2\20\1\0\5\20\1\134\34\20\2\0\3\20\10\0"+
    "\2\20\1\0\13\20\1\135\26\20\2\0\3\20\10\0"+
    "\2\20\1\0\36\20\1\136\3\20\2\0\3\20\10\0"+
    "\2\20\1\0\37\20\1\137\2\20\2\0\3\20\24\0"+
    "\1\140\53\0\1\141\53\0\2\20\1\0\4\20\1\142"+
    "\35\20\2\0\3\20\10\0\2\20\1\0\12\20\1\143"+
    "\27\20\2\0\3\20\10\0\2\20\1\0\17\20\1\144"+
    "\22\20\2\0\3\20\10\0\2\20\1\0\31\20\1\145"+
    "\10\20\2\0\3\20\10\0\2\20\1\0\23\20\1\146"+
    "\16\20\2\0\3\20\10\0\2\20\1\0\34\20\1\147"+
    "\5\20\2\0\3\20\10\0\2\20\1\0\1\20\1\150"+
    "\40\20\2\0\3\20\10\0\2\20\1\0\7\20\1\151"+
    "\32\20\2\0\3\20\10\0\2\20\1\0\16\20\1\152"+
    "\23\20\2\0\3\20\10\0\2\20\1\0\22\20\1\152"+
    "\17\20\2\0\3\20\25\0\1\153\53\0\1\154\52\0"+
    "\2\20\1\0\5\20\1\155\34\20\2\0\3\20\10\0"+
    "\2\20\1\0\13\20\1\156\26\20\2\0\3\20\10\0"+
    "\2\20\1\0\1\20\1\157\40\20\2\0\3\20\10\0"+
    "\2\20\1\0\32\20\1\152\7\20\2\0\3\20\10\0"+
    "\2\20\1\0\7\20\1\160\32\20\2\0\3\20\10\0"+
    "\2\20\1\0\35\20\1\152\4\20\2\0\3\20\10\0"+
    "\2\20\1\0\3\20\1\161\36\20\2\0\3\20\10\0"+
    "\2\20\1\0\11\20\1\162\30\20\2\0\3\20\23\0"+
    "\1\163\53\0\1\164\54\0\2\20\1\0\2\20\1\152"+
    "\37\20\2\0\3\20\10\0\2\20\1\0\10\20\1\152"+
    "\31\20\2\0\3\20\10\0\2\20\1\0\15\20\1\136"+
    "\24\20\2\0\3\20\10\0\2\20\1\0\21\20\1\137"+
    "\20\20\2\0\3\20\10\0\2\20\1\0\4\20\1\165"+
    "\35\20\2\0\3\20\10\0\2\20\1\0\12\20\1\166"+
    "\27\20\2\0\3\20\22\0\1\167\53\0\1\170\55\0"+
    "\2\20\1\0\2\20\1\136\37\20\2\0\3\20\10\0"+
    "\2\20\1\0\10\20\1\137\31\20\2\0\3\20\35\0"+
    "\1\15\55\0\1\15\36\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5150];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\10\0\5\11\1\1\1\11\17\1\5\11\20\1\2\0"+
    "\2\1\4\0\13\1\2\0\13\1\2\0\12\1\2\0"+
    "\11\1\2\0\6\1\2\0\2\1\2\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[120];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	String location = "MAIN PROGRAM";
	
	int bracket = 0;
	
	public F77INSTIf() {
    }
	
	@Override
	public void setInputFile(IPath file) throws FileNotFoundException {
		super.setInputFile(file);
		this.zzReader = new FileReader(file.toOSString());
	}
	int LAST_STATE = LINE;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public F77INSTIf(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 170) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public List<Violation> run() throws java.io.IOException, JFlexException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {     return getViolations();
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { yybegin(LINE);
            }
          case 16: break;
          case 2: 
            { yybegin(COMMENT);
            }
          case 17: break;
          case 3: 
            { yybegin(NEW_LINE);
            }
          case 18: break;
          case 4: 
            { throw new JFlexException( new Exception("Illegal character <" + yytext() + ">") );
            }
          case 19: break;
          case 5: 
            { 
            }
          case 20: break;
          case 6: 
            { location = location + " " + yytext();
								 yybegin(COMMENT);
            }
          case 21: break;
          case 7: 
            { if (yycolumn == 5) yybegin(LAST_STATE);
            }
          case 22: break;
          case 8: 
            { LAST_STATE = LINE;
								 yybegin(NEW_LINE);
            }
          case 23: break;
          case 9: 
            { LAST_STATE = IF;
								 yybegin(NEW_LINE);
            }
          case 24: break;
          case 10: 
            { bracket=1; yybegin(BRAKET);
            }
          case 25: break;
          case 11: 
            { bracket++;
            }
          case 26: break;
          case 12: 
            { bracket--; if(bracket==0) yybegin(COMA);
            }
          case 27: break;
          case 13: 
            { setError(location,"The arithmetic if is not allowed.", yyline + 1);
								 yybegin(COMMENT);
            }
          case 28: break;
          case 14: 
            { yybegin(IF);
            }
          case 29: break;
          case 15: 
            { location = yytext(); yybegin(NAMING);
            }
          case 30: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
