/* The following code was generated by JFlex 1.6.1 */

/************************************************************************************************/
/* i-Code CNES is a static code analyzer.                                                       */
/* This software is a free software, under the terms of the Eclipse Public License version 1.0. */ 
/* http://www.eclipse.org/legal/epl-v10.html                                                    */
/************************************************************************************************/ 

/*****************************************************************************/
/* This file is used to generate a rule checker for F90.DATA.Array rule.	 */
/* For further information on this, we advise you to refer to RNC manuals.	 */
/* As many comments have been done on the ExampleRule.lex file, this file    */
/* will restrain its comments on modifications.								 */
/*																			 */
/*****************************************************************************/

package fr.cnes.analysis.tools.fortran90.rules;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.LinkedList;
import java.util.List;

import org.eclipse.core.runtime.IPath;

import fr.cnes.analysis.tools.analyzer.datas.AbstractRule;
import fr.cnes.analysis.tools.analyzer.datas.Violation;
import fr.cnes.analysis.tools.analyzer.exception.JFlexException;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>lex/F90DATAArray.lex</tt>
 */
public class F90DATAArray extends AbstractRule {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int NAMING = 4;
  public static final int NEW_LINE = 6;
  public static final int LINE = 8;
  public static final int PARAM = 10;
  public static final int DECLARATION = 12;
  public static final int WAIT = 14;
  public static final int VERIFICATION = 16;
  public static final int VERIFICATION_DIM = 18;
  public static final int WAIT_2 = 20;
  public static final int VERIF_PARAM = 22;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9,  9, 10, 10, 11, 11
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\34\1\35\1\37\1\36\1\36\22\0\1\34\1\1\1\33"+
    "\3\0\1\42\1\32\1\40\1\41\6\0\12\31\1\43\6\0\1\20"+
    "\1\16\1\5\1\14\1\13\1\2\1\17\1\24\1\26\2\25\1\22"+
    "\1\21\1\4\1\10\1\11\1\25\1\12\1\27\1\6\1\3\2\25"+
    "\1\23\2\25\4\0\1\30\1\0\1\20\1\16\1\5\1\14\1\13"+
    "\1\2\1\17\1\24\1\26\2\25\1\22\1\21\1\4\1\10\1\11"+
    "\1\25\1\12\1\27\1\6\1\3\2\25\1\23\2\25\12\0\1\37"+
    "\252\0\2\7\115\0\1\15\u1ea8\0\1\37\1\37\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\14\0\1\1\1\2\7\1\1\3\1\4\1\5\1\6"+
    "\5\1\7\5\1\7\1\10\1\11\4\5\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\5\1\20\10\0\1\21"+
    "\11\0\1\22\1\0\1\23\1\24\25\0\1\25\23\0"+
    "\1\26\17\0\1\27\5\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\264\0\330\0\374"+
    "\0\u0120\0\u0144\0\u0168\0\u018c\0\u01b0\0\u01b0\0\u01d4\0\u01f8"+
    "\0\u021c\0\u0240\0\u0264\0\u0288\0\u02ac\0\u01b0\0\u01b0\0\u01b0"+
    "\0\u02d0\0\u02f4\0\u0318\0\u033c\0\u0360\0\u0384\0\u01d4\0\u01f8"+
    "\0\u021c\0\u0240\0\u0264\0\u0288\0\u02ac\0\u03a8\0\u01b0\0\u01b0"+
    "\0\u03cc\0\u03f0\0\u0414\0\u0438\0\u045c\0\u0480\0\u01b0\0\u04a4"+
    "\0\u04c8\0\u01b0\0\u04ec\0\u0510\0\u0534\0\u0558\0\u057c\0\u05a0"+
    "\0\u05c4\0\u0288\0\u02ac\0\u05e8\0\u01b0\0\u060c\0\u0630\0\u0654"+
    "\0\u0678\0\u069c\0\u06c0\0\u03cc\0\u03f0\0\u06e4\0\u01b0\0\u0708"+
    "\0\u01b0\0\u01b0\0\u072c\0\u0750\0\u0774\0\u0798\0\u07bc\0\u07e0"+
    "\0\u0804\0\u0828\0\u084c\0\u0870\0\u0894\0\u08b8\0\u08dc\0\u0900"+
    "\0\u0924\0\u0948\0\u096c\0\u0990\0\u09b4\0\u09d8\0\u09fc\0\u01b0"+
    "\0\u0a20\0\u0a44\0\u0a68\0\u0a8c\0\u0ab0\0\u0ad4\0\u0af8\0\u0b1c"+
    "\0\u0b40\0\u0b64\0\u0b88\0\u0bac\0\u0bd0\0\u0bf4\0\u0c18\0\u0c3c"+
    "\0\u0c60\0\u0c84\0\u0ca8\0\u01b0\0\u0ccc\0\u0cf0\0\u0d14\0\u0d38"+
    "\0\u0d5c\0\u0d80\0\u0da4\0\u0dc8\0\u0dec\0\u0e10\0\u0e34\0\u0e58"+
    "\0\u0e7c\0\u0ea0\0\u0ec4\0\u01b0\0\u0ee8\0\u0f0c\0\u0f30\0\u0f54"+
    "\0\u0f78";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\15\1\16\1\17\4\15\1\20\1\15\1\21\3\15"+
    "\1\22\3\15\1\23\4\15\1\20\1\22\2\15\1\24"+
    "\1\25\1\15\1\26\2\27\4\15\1\30\1\16\33\30"+
    "\1\26\2\27\5\30\1\16\5\31\1\30\5\31\1\30"+
    "\12\31\5\30\1\26\2\27\4\30\1\15\1\16\1\17"+
    "\2\15\1\32\1\15\1\33\1\15\1\21\1\34\1\15"+
    "\1\35\1\22\3\15\1\23\1\36\3\15\1\33\1\22"+
    "\2\15\1\24\1\25\3\30\1\27\4\15\1\30\1\16"+
    "\1\37\4\30\1\40\1\30\1\41\3\30\1\42\3\30"+
    "\1\43\4\30\1\40\1\42\2\30\1\44\1\45\1\30"+
    "\1\26\1\30\1\27\5\30\1\16\5\46\1\30\5\46"+
    "\1\30\12\46\5\30\1\26\2\27\1\47\1\50\1\51"+
    "\2\30\1\16\5\52\1\30\5\52\1\30\12\52\5\30"+
    "\1\26\2\27\5\30\1\16\12\30\1\53\20\30\1\26"+
    "\2\27\3\30\1\54\1\30\1\16\5\55\1\30\5\55"+
    "\1\30\12\55\1\30\1\56\3\30\1\26\2\27\1\47"+
    "\1\57\3\30\1\16\5\60\1\30\5\60\1\30\12\60"+
    "\1\30\1\61\3\30\1\26\2\27\1\47\1\62\3\30"+
    "\1\16\33\30\1\26\2\27\3\30\1\63\1\30\1\16"+
    "\5\64\1\30\5\64\1\30\12\64\5\30\1\26\2\27"+
    "\4\30\47\0\1\65\44\0\1\66\51\0\1\67\34\0"+
    "\1\70\50\0\1\71\33\0\32\72\1\15\11\72\33\73"+
    "\1\15\10\73\2\0\5\31\1\0\5\31\1\0\14\31"+
    "\2\0\1\74\1\0\1\74\1\0\1\75\13\0\1\76"+
    "\13\0\1\77\23\0\1\100\52\0\1\101\40\0\1\102"+
    "\43\0\1\103\35\0\5\46\1\0\5\46\1\0\14\46"+
    "\46\0\1\104\1\30\1\104\7\0\5\105\1\0\5\105"+
    "\1\0\14\105\2\0\1\106\1\0\1\106\1\0\1\107"+
    "\12\0\1\110\16\0\1\110\60\0\1\111\2\0\5\55"+
    "\1\0\5\55\1\0\14\55\43\0\1\56\14\0\5\60"+
    "\1\0\5\60\1\0\14\60\43\0\1\61\55\0\1\112"+
    "\2\0\5\64\1\0\5\64\1\0\14\64\16\0\1\113"+
    "\45\0\1\114\45\0\1\115\51\0\1\116\41\0\1\117"+
    "\63\0\1\74\1\0\1\74\1\0\1\75\24\0\1\120"+
    "\42\0\1\121\31\0\1\122\55\0\1\123\26\0\1\124"+
    "\57\0\1\125\60\0\1\106\1\0\1\106\1\0\1\107"+
    "\24\0\1\126\27\0\1\127\51\0\1\130\35\0\1\131"+
    "\11\0\1\132\36\0\1\133\34\0\1\134\51\0\1\135"+
    "\44\0\1\136\44\0\1\137\52\0\1\140\37\0\1\141"+
    "\34\0\1\142\16\0\1\142\30\0\1\143\36\0\1\144"+
    "\47\0\1\145\44\0\1\146\42\0\1\147\41\0\1\150"+
    "\55\0\1\151\43\0\1\152\41\0\1\153\35\0\1\145"+
    "\4\0\1\154\46\0\1\155\26\0\1\101\42\0\1\156"+
    "\46\0\1\157\16\0\1\157\17\0\1\160\55\0\1\161"+
    "\47\0\1\162\26\0\1\163\53\0\1\164\43\0\1\165"+
    "\35\0\1\166\51\0\1\167\43\0\1\170\45\0\1\171"+
    "\11\0\1\171\24\0\1\172\53\0\1\173\26\0\1\174"+
    "\61\0\1\164\30\0\1\175\60\0\1\140\26\0\1\154"+
    "\47\0\1\140\42\0\1\176\22\0\1\170\1\0\1\170"+
    "\14\0\1\177\16\0\1\177\21\0\1\164\44\0\1\151"+
    "\50\0\1\151\40\0\1\200\16\0\1\200\27\0\1\201"+
    "\41\0\1\202\37\0\1\151\52\0\1\203\34\0\1\204"+
    "\44\0\1\205\45\0\1\206\16\0\1\206\32\0\1\207"+
    "\11\0\1\207\23\0\1\210\16\0\1\210\25\0\1\211"+
    "\37\0\1\140\37\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3996];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\14\0\2\11\7\1\3\11\16\1\2\11\6\1\1\11"+
    "\2\1\1\11\2\1\10\0\1\11\11\0\1\11\1\0"+
    "\2\11\25\0\1\11\23\0\1\11\17\0\1\11\5\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	String location = "MAIN PROGRAM"; 
	/** LIst of violations **/
  	List<Violation> list = new LinkedList<Violation>();
  	/** Parameters' function list **/
  	List<String> parameters = new LinkedList<String>();
  	int parenthese = 0;
  	boolean error = false;
	
	public F90DATAArray() {
    }
	
	@Override
	public void setInputFile(IPath file) throws FileNotFoundException {
		super.setInputFile(file);
		this.zzReader = new FileReader(file.toOSString());
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public F90DATAArray(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 188) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public List<Violation> run() throws java.io.IOException, JFlexException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {  	return getViolations(); 
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { yybegin(LINE);
            }
          case 24: break;
          case 2: 
            { yybegin(COMMENT);
            }
          case 25: break;
          case 3: 
            { yybegin(NEW_LINE);
            }
          case 26: break;
          case 4: 
            { throw new JFlexException( new Exception("Illegal character <" + yytext() + ">") );
            }
          case 27: break;
          case 5: 
            { 
            }
          case 28: break;
          case 6: 
            { location = location + " " + yytext(); yybegin(COMMENT);
            }
          case 29: break;
          case 7: 
            { parameters.add(yytext());
            }
          case 30: break;
          case 8: 
            { parenthese++;
            }
          case 31: break;
          case 9: 
            { parenthese--;
							 if (parenthese==0) 
							 yybegin(LINE);
            }
          case 32: break;
          case 10: 
            { if (!parameters.contains(yytext())&&(location.toLowerCase().contains("function")||location.toLowerCase().contains("subroutine")))
							setError(location,"the dimention's array must be declared as parameters' function.", yyline+1);
            }
          case 33: break;
          case 11: 
            { if (location.toLowerCase().contains("function")||location.toLowerCase().contains("subroutine"))
							    setError(location,"the dimention's array must be declared as parameters' function.", yyline+1);
            }
          case 34: break;
          case 12: 
            { parenthese--;
							 if (parenthese==0) 
							 yybegin(DECLARATION);
            }
          case 35: break;
          case 13: 
            { if (!parameters.contains(yytext())&&(location.toLowerCase().contains("function")||location.toLowerCase().contains("subroutine")))
								error = true;
            }
          case 36: break;
          case 14: 
            { if(location.toLowerCase().contains("function")||location.toLowerCase().contains("subroutine"))
								error = true;
            }
          case 37: break;
          case 15: 
            { parenthese--;
							 if (parenthese==0) 
							 yybegin(WAIT_2);
            }
          case 38: break;
          case 16: 
            { if (parameters.contains(yytext())&&error) setError(location,"the dimention's array must be declared as parameters' function.", yyline+1);
            }
          case 39: break;
          case 17: 
            { location = location + " " + yytext().replaceAll("\\(","").trim(); parenthese=1;  parameters.clear(); yybegin(PARAM);
            }
          case 40: break;
          case 18: 
            { if(parameters.contains(yytext().replaceAll("\\(", "").trim())) { parenthese=1; yybegin(VERIFICATION);}
            }
          case 41: break;
          case 19: 
            { yybegin(DECLARATION);
            }
          case 42: break;
          case 20: 
            { yybegin(VERIF_PARAM);
            }
          case 43: break;
          case 21: 
            { yybegin(WAIT);
            }
          case 44: break;
          case 22: 
            { location = yytext(); yybegin(NAMING);
            }
          case 45: break;
          case 23: 
            { error = false; yybegin(VERIFICATION_DIM);
            }
          case 46: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
