/* The following code was generated by JFlex 1.6.1 */

/************************************************************************************************/
/* i-Code CNES is a static code analyzer.                                                       */
/* This software is a free software, under the terms of the Eclipse Public License version 1.0. */ 
/* http://www.eclipse.org/legal/epl-v10.html                                                    */
/************************************************************************************************/ 

/*****************************************************************************/
/* This file is used to generate a rule checker for F90.REF.Open rule.		 */
/* For further information on this, we advise you to refer to RNC manuals.	 */
/* As many comments have been done on the ExampleRule.lex file, this file    */
/* will restrain its comments on modifications.								 */
/*																			 */
/*****************************************************************************/

package fr.cnes.analysis.tools.fortran90.rules;

import java.io.FileNotFoundException;
import java.io.FileReader;

import java.util.List;

import org.eclipse.core.runtime.IPath;




import fr.cnes.analysis.tools.analyzer.exception.JFlexException;
import fr.cnes.analysis.tools.analyzer.datas.AbstractRule;
import fr.cnes.analysis.tools.analyzer.datas.Violation;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>lex/F90REFOpen.lex</tt>
 */
public class F90REFOpen extends AbstractRule {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int NAMING = 4;
  public static final int NEW_LINE = 6;
  public static final int LINE = 8;
  public static final int OPEN = 10;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\30\1\3\1\41\1\42\1\40\22\0\1\30\1\1\1\33"+
    "\1\2\2\0\1\43\1\32\10\0\12\25\7\0\1\22\1\20\1\7"+
    "\1\16\1\15\1\4\1\21\1\34\1\26\1\31\1\36\1\24\1\23"+
    "\1\6\1\12\1\13\1\31\1\14\1\27\1\10\1\5\1\31\1\37"+
    "\3\31\4\0\1\25\1\0\1\22\1\20\1\7\1\16\1\15\1\4"+
    "\1\21\1\34\1\26\1\31\1\36\1\24\1\23\1\6\1\12\1\13"+
    "\1\31\1\14\1\27\1\10\1\5\1\31\1\37\3\31\12\0\1\41"+
    "\252\0\2\11\115\0\1\17\u1ea8\0\1\41\1\41\u0100\0\1\35\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udee5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\14\1\1\3\1\1\1\2\1\4"+
    "\1\3\1\5\1\2\1\1\1\6\5\1\1\7\1\0"+
    "\3\1\2\0\1\1\1\0\2\1\1\0\1\1\3\0"+
    "\2\1\13\0\1\1\1\0\2\1\2\0\1\1\1\0"+
    "\2\1\1\0\1\1\3\0\2\1\11\0\2\1\2\0"+
    "\1\1\1\0\1\10\2\1\1\0\1\1\3\0\2\1"+
    "\2\0\1\11\6\0\2\1\2\0\1\1\1\0\2\1"+
    "\1\0\1\1\4\0\2\1\10\0\1\1\1\0\1\1"+
    "\2\0\1\1\1\0\2\1\1\0\1\12\4\0\2\1"+
    "\3\0\1\13\2\0\1\14\3\0\1\1\2\0\1\1"+
    "\1\0\1\1\3\0\3\1\2\0\1\15\1\0\1\16"+
    "\2\0\1\12\2\0\1\1\3\0\1\1\2\0\1\17"+
    "\31\0\2\1";

  private static int [] zzUnpackAction() {
    int [] result = new int[221];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\264\0\264\0\330"+
    "\0\374\0\u0120\0\u0144\0\u0168\0\u018c\0\u01b0\0\u01d4\0\u01f8"+
    "\0\u021c\0\u0240\0\u0264\0\264\0\u0288\0\u0288\0\u0288\0\u0288"+
    "\0\u02ac\0\u02d0\0\u02d0\0\u0288\0\u02f4\0\u0318\0\u033c\0\u0360"+
    "\0\u0384\0\u03a8\0\u03cc\0\u03f0\0\u0414\0\u0438\0\u045c\0\u0480"+
    "\0\u04a4\0\u04c8\0\u04ec\0\u0510\0\u0534\0\u0558\0\u057c\0\u05a0"+
    "\0\u05c4\0\u05e8\0\u060c\0\u0630\0\u0654\0\u0678\0\u069c\0\u02d0"+
    "\0\u06c0\0\u06e4\0\u0708\0\u072c\0\u0750\0\u0774\0\u03a8\0\u0798"+
    "\0\u07bc\0\u07e0\0\u0804\0\u0828\0\u084c\0\u0870\0\u0894\0\u08b8"+
    "\0\u08dc\0\u0900\0\u0924\0\u0948\0\u096c\0\u0990\0\u09b4\0\u09d8"+
    "\0\u09fc\0\u0a20\0\u0a44\0\u0a68\0\u0a8c\0\u0ab0\0\u0ad4\0\u0af8"+
    "\0\u0b1c\0\u0b40\0\u0b64\0\u0b88\0\u0bac\0\u0bd0\0\u0438\0\u0bf4"+
    "\0\u0c18\0\u0c3c\0\u0c60\0\u0c84\0\u0ca8\0\u0ccc\0\u0cf0\0\u0d14"+
    "\0\u0d38\0\u0d5c\0\u0288\0\u0d80\0\u0da4\0\u0dc8\0\u0dec\0\u0e10"+
    "\0\u0e34\0\u0e58\0\u0e7c\0\u0ea0\0\u0ec4\0\u0ee8\0\u0f0c\0\u0f30"+
    "\0\u0f54\0\u0f78\0\u0f9c\0\u0fc0\0\u0fe4\0\u1008\0\u102c\0\u1050"+
    "\0\u1074\0\u1098\0\u10bc\0\u10e0\0\u1104\0\u1128\0\u114c\0\u1170"+
    "\0\u1194\0\u11b8\0\u11dc\0\u1200\0\u1224\0\u1248\0\u126c\0\u1290"+
    "\0\u12b4\0\u12d8\0\u12fc\0\u0438\0\u1320\0\u1344\0\u1368\0\u138c"+
    "\0\u13b0\0\u13d4\0\u13f8\0\u141c\0\u1440\0\u0288\0\u1464\0\u1488"+
    "\0\u0288\0\u14ac\0\u14d0\0\u14f4\0\u1518\0\u153c\0\u1560\0\u1584"+
    "\0\u15a8\0\u15cc\0\u15f0\0\u1614\0\u1638\0\u165c\0\u1680\0\u16a4"+
    "\0\u16c8\0\u16ec\0\u0288\0\u1710\0\u0288\0\u1734\0\u1758\0\u165c"+
    "\0\u177c\0\u17a0\0\u17c4\0\u17e8\0\u180c\0\u1830\0\u1854\0\u1878"+
    "\0\u189c\0\u0288\0\u18c0\0\u18e4\0\u1908\0\u192c\0\u1950\0\u1974"+
    "\0\u1998\0\u19bc\0\u19e0\0\u1a04\0\u1a28\0\u1a4c\0\u1a70\0\u1a94"+
    "\0\u1ab8\0\u1adc\0\u1b00\0\u1b24\0\u1b48\0\u1b6c\0\u1b90\0\u1bb4"+
    "\0\u1bd8\0\u1bfc\0\u1c20\0\u0630\0\u0678";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[221];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\2\6\1\10\4\11\1\12\1\13\1\14"+
    "\3\11\1\15\3\11\1\16\1\11\1\17\1\20\1\21"+
    "\1\6\1\11\1\22\1\23\1\11\1\6\2\11\3\24"+
    "\1\6\1\25\1\26\1\25\1\27\34\25\1\27\2\30"+
    "\2\25\1\26\1\25\1\27\5\31\1\25\5\31\1\25"+
    "\5\31\1\25\2\31\1\25\1\31\2\25\1\31\1\25"+
    "\2\31\1\27\2\30\1\25\1\30\1\26\42\30\1\25"+
    "\1\32\1\33\1\34\1\35\1\36\3\25\1\37\1\25"+
    "\1\40\3\25\1\41\6\25\1\37\1\41\10\25\3\30"+
    "\1\42\23\0\1\43\24\0\1\44\1\45\3\46\1\47"+
    "\5\46\1\50\7\46\1\51\1\0\1\46\2\0\1\46"+
    "\1\0\2\46\10\0\1\44\4\46\1\47\5\46\1\50"+
    "\7\46\1\51\1\0\1\46\2\0\1\46\1\0\2\46"+
    "\12\0\1\52\14\0\1\43\24\0\1\44\4\46\1\47"+
    "\1\46\1\53\3\46\1\50\7\46\1\51\1\0\1\46"+
    "\2\0\1\46\1\0\2\46\10\0\1\44\4\46\1\47"+
    "\2\46\1\54\2\46\1\50\7\46\1\51\1\0\1\46"+
    "\2\0\1\46\1\0\2\46\11\0\1\55\15\0\1\43"+
    "\24\0\1\44\4\46\1\47\1\56\4\46\1\50\7\46"+
    "\1\51\1\0\1\46\2\0\1\46\1\0\2\46\10\0"+
    "\1\57\4\0\1\47\1\0\1\60\3\0\1\50\3\0"+
    "\1\61\2\0\1\47\1\50\20\0\1\44\1\46\1\62"+
    "\2\46\1\47\5\46\1\50\7\46\1\51\1\0\1\46"+
    "\2\0\1\46\1\0\2\46\10\0\1\44\1\63\3\46"+
    "\1\47\5\46\1\50\7\46\1\51\1\0\1\46\2\0"+
    "\1\46\1\0\2\46\4\0\23\64\1\65\6\64\1\25"+
    "\11\64\23\66\1\67\7\66\1\25\10\66\50\0\5\31"+
    "\1\0\5\31\1\0\10\31\1\0\1\31\2\0\1\31"+
    "\1\0\2\31\4\0\3\70\1\25\40\70\11\0\1\71"+
    "\14\0\1\71\23\0\1\72\47\0\1\73\43\0\1\74"+
    "\40\0\1\75\1\76\33\0\3\25\1\0\24\25\1\77"+
    "\7\25\1\0\1\25\1\77\1\25\12\0\1\100\35\0"+
    "\1\46\1\101\3\46\1\0\5\46\1\0\10\46\1\0"+
    "\1\46\2\0\1\46\1\0\2\46\10\0\2\46\1\102"+
    "\2\46\1\0\5\46\1\0\10\46\1\0\1\46\2\0"+
    "\1\46\1\0\2\46\10\0\5\46\1\0\5\46\1\0"+
    "\10\46\1\0\1\46\2\0\1\46\1\0\2\46\12\0"+
    "\1\103\42\0\1\104\42\0\1\46\1\105\3\46\1\0"+
    "\5\46\1\0\10\46\1\0\1\46\2\0\1\46\1\0"+
    "\2\46\14\0\1\106\37\0\5\46\1\0\3\46\1\107"+
    "\1\46\1\0\10\46\1\0\1\46\2\0\1\46\1\0"+
    "\2\46\10\0\5\46\1\0\1\110\4\46\1\0\10\46"+
    "\1\0\1\46\2\0\1\46\1\0\2\46\24\0\1\111"+
    "\27\0\5\46\1\0\4\46\1\112\1\0\10\46\1\0"+
    "\1\46\2\0\1\46\1\0\2\46\11\0\1\113\52\0"+
    "\1\114\41\0\1\115\35\0\4\46\1\116\1\0\5\46"+
    "\1\0\10\46\1\0\1\46\2\0\1\46\1\0\2\46"+
    "\10\0\5\46\1\0\5\46\1\0\1\117\7\46\1\0"+
    "\1\46\2\0\1\46\1\0\2\46\4\0\32\64\1\25"+
    "\23\64\1\120\17\64\1\25\11\64\33\66\1\25\22\66"+
    "\1\121\20\66\1\25\10\66\24\0\1\122\54\0\2\123"+
    "\24\0\1\124\7\0\1\124\33\0\1\125\7\0\1\125"+
    "\30\0\1\126\51\0\1\127\37\0\1\130\31\0\2\46"+
    "\1\131\2\46\1\0\5\46\1\0\10\46\1\0\1\46"+
    "\2\0\1\46\1\0\2\46\10\0\3\46\1\132\1\46"+
    "\1\0\5\46\1\0\10\46\1\0\1\46\2\0\1\46"+
    "\1\0\2\46\14\0\1\133\53\0\1\134\27\0\5\46"+
    "\1\0\5\46\1\0\1\135\7\46\1\0\1\46\2\0"+
    "\1\46\1\0\2\46\21\0\1\136\32\0\2\46\1\137"+
    "\2\46\1\0\5\46\1\0\10\46\1\0\1\46\2\0"+
    "\1\46\1\0\2\46\10\0\3\46\1\140\1\46\1\0"+
    "\5\46\1\0\1\46\1\141\6\46\1\0\1\46\2\0"+
    "\1\46\1\0\2\46\20\0\1\142\33\0\1\46\1\143"+
    "\3\46\1\0\5\46\1\0\10\46\1\0\1\46\2\0"+
    "\1\46\1\0\2\46\12\0\1\144\47\0\1\145\47\0"+
    "\1\146\31\0\5\46\1\0\3\46\1\147\1\46\1\0"+
    "\10\46\1\0\1\46\2\0\1\46\1\0\2\46\10\0"+
    "\5\46\1\0\2\46\1\150\2\46\1\0\10\46\1\0"+
    "\1\46\2\0\1\46\1\0\2\46\4\0\16\64\1\151"+
    "\13\64\1\25\11\64\16\66\1\152\14\66\1\25\10\66"+
    "\15\0\1\153\34\0\1\154\45\0\1\155\44\0\1\156"+
    "\14\0\1\156\37\0\1\157\31\0\1\160\40\0\1\161"+
    "\42\0\3\46\1\162\1\46\1\0\5\46\1\0\10\46"+
    "\1\0\1\46\2\0\1\46\1\0\2\46\10\0\4\46"+
    "\1\163\1\0\5\46\1\0\10\46\1\0\1\46\2\0"+
    "\1\46\1\0\2\46\21\0\1\164\42\0\1\165\33\0"+
    "\5\46\1\0\2\46\1\166\2\46\1\0\10\46\1\0"+
    "\1\46\2\0\1\46\1\0\2\46\20\0\1\167\33\0"+
    "\5\46\1\0\3\46\1\170\1\46\1\0\10\46\1\0"+
    "\1\46\2\0\1\46\1\0\2\46\10\0\5\46\1\0"+
    "\2\46\1\171\2\46\1\0\10\46\1\0\1\46\2\0"+
    "\1\46\1\0\2\46\16\0\1\172\35\0\5\46\1\0"+
    "\5\46\1\0\4\46\1\173\3\46\1\0\1\46\2\0"+
    "\1\46\1\0\2\46\13\0\1\174\43\0\1\175\11\0"+
    "\1\176\27\0\1\177\42\0\5\46\1\0\2\46\1\200"+
    "\2\46\1\0\10\46\1\0\1\46\2\0\1\46\1\0"+
    "\2\46\10\0\5\46\1\0\1\201\4\46\1\0\10\46"+
    "\1\0\1\46\2\0\1\46\1\0\2\46\4\0\5\64"+
    "\1\202\24\64\1\25\11\64\5\66\1\203\25\66\1\25"+
    "\10\66\12\0\1\204\53\0\1\205\31\0\1\206\43\0"+
    "\1\207\40\0\1\210\62\0\1\211\23\0\4\46\1\212"+
    "\1\0\5\46\1\0\10\46\1\0\1\46\2\0\1\46"+
    "\1\0\2\46\10\0\5\46\1\213\5\46\1\0\6\46"+
    "\1\214\1\46\1\0\1\46\2\0\1\46\1\0\2\46"+
    "\20\0\1\215\41\0\1\216\35\0\5\46\1\0\1\217"+
    "\4\46\1\0\10\46\1\0\1\46\2\0\1\46\1\0"+
    "\2\46\10\0\1\220\43\0\5\46\1\0\4\46\1\221"+
    "\1\0\10\46\1\0\1\46\2\0\1\46\1\0\2\46"+
    "\10\0\5\46\1\0\5\46\1\0\2\46\1\222\5\46"+
    "\1\0\1\46\2\0\1\46\1\0\2\46\11\0\1\223"+
    "\42\0\5\46\1\0\3\46\1\224\1\46\1\0\10\46"+
    "\1\0\1\46\2\0\1\46\1\0\2\46\14\0\1\225"+
    "\50\0\1\226\42\0\1\227\53\0\1\230\23\0\1\231"+
    "\4\46\1\0\5\46\1\0\10\46\1\0\1\46\2\0"+
    "\1\46\1\0\2\46\10\0\1\46\1\232\3\46\1\0"+
    "\5\46\1\0\10\46\1\0\1\46\2\0\1\46\1\0"+
    "\2\46\4\0\24\64\1\233\5\64\1\25\11\64\24\66"+
    "\1\234\6\66\1\25\10\66\37\0\1\235\14\0\1\236"+
    "\44\0\1\237\14\0\1\237\24\0\1\240\53\0\1\241"+
    "\7\0\1\241\31\0\1\242\32\0\5\46\1\243\5\46"+
    "\1\0\10\46\1\0\1\46\2\0\1\46\1\0\2\46"+
    "\16\0\1\244\35\0\5\46\1\0\1\245\4\46\1\0"+
    "\10\46\1\0\1\46\2\0\1\46\1\0\2\46\10\0"+
    "\1\246\44\0\1\247\42\0\1\46\1\250\3\46\1\0"+
    "\5\46\1\0\10\46\1\0\1\46\2\0\1\46\1\0"+
    "\2\46\26\0\1\251\25\0\1\46\1\252\3\46\1\0"+
    "\5\46\1\0\10\46\1\0\1\46\2\0\1\46\1\0"+
    "\2\46\10\0\5\46\1\0\5\46\1\0\3\46\1\224"+
    "\4\46\1\0\1\46\2\0\1\46\1\0\2\46\14\0"+
    "\1\253\44\0\1\243\14\0\1\243\33\0\1\254\47\0"+
    "\1\255\36\0\1\256\32\0\5\46\1\0\5\46\1\0"+
    "\2\46\1\257\5\46\1\0\1\46\2\0\1\46\1\0"+
    "\2\46\10\0\4\46\1\260\1\0\5\46\1\0\10\46"+
    "\1\0\1\46\2\0\1\46\1\0\2\46\4\0\15\64"+
    "\1\261\14\64\1\25\11\64\15\66\1\262\15\66\1\25"+
    "\10\66\6\0\1\263\47\0\1\264\65\0\1\265\22\0"+
    "\1\266\14\0\1\242\11\0\1\242\13\0\1\267\37\0"+
    "\1\270\41\0\2\46\1\224\2\46\1\0\5\46\1\0"+
    "\10\46\1\0\1\46\2\0\1\46\1\0\2\46\26\0"+
    "\1\271\31\0\1\272\37\0\4\46\1\273\1\0\5\46"+
    "\1\0\10\46\1\0\1\46\2\0\1\46\1\0\2\46"+
    "\13\0\1\274\40\0\5\46\1\0\2\46\1\173\2\46"+
    "\1\0\10\46\1\0\1\46\2\0\1\46\1\0\2\46"+
    "\15\0\1\275\14\0\1\275\22\0\1\276\61\0\1\256"+
    "\24\0\5\25\1\0\5\25\1\0\10\25\1\0\1\25"+
    "\2\0\1\25\1\0\2\25\10\0\3\46\1\173\1\46"+
    "\1\0\5\46\1\0\10\46\1\0\1\46\2\0\1\46"+
    "\1\0\2\46\10\0\5\46\1\275\5\46\1\0\6\46"+
    "\1\277\1\46\1\0\1\46\2\0\1\46\1\0\2\46"+
    "\4\0\13\64\1\300\14\64\1\261\1\64\1\25\7\64"+
    "\1\261\1\64\13\66\1\301\14\66\1\262\2\66\1\25"+
    "\6\66\1\262\1\66\6\0\1\302\51\0\1\303\35\0"+
    "\1\256\44\0\1\230\45\0\1\304\14\0\1\304\21\0"+
    "\5\46\1\304\5\46\1\0\10\46\1\0\1\46\2\0"+
    "\1\46\1\0\2\46\21\0\1\270\34\0\1\274\51\0"+
    "\1\230\33\0\2\46\1\173\2\46\1\0\5\46\1\0"+
    "\10\46\1\0\1\46\2\0\1\46\1\0\2\46\4\0"+
    "\14\64\1\305\15\64\1\25\11\64\14\66\1\306\16\66"+
    "\1\25\10\66\12\0\1\307\37\0\1\230\35\0\12\64"+
    "\1\310\17\64\1\25\11\64\12\66\1\311\20\66\1\25"+
    "\10\66\7\0\1\312\34\0\7\64\1\313\22\64\1\25"+
    "\11\64\7\66\1\314\23\66\1\25\10\66\15\0\1\315"+
    "\26\0\15\64\1\316\14\64\1\25\11\64\15\66\1\317"+
    "\15\66\1\25\10\66\16\0\1\320\25\0\16\64\1\321"+
    "\13\64\1\25\11\64\16\66\1\322\14\66\1\25\10\66"+
    "\5\0\1\323\36\0\5\64\1\324\24\64\1\25\11\64"+
    "\5\66\1\325\25\66\1\25\10\66\14\0\1\326\27\0"+
    "\14\64\1\327\15\64\1\25\11\64\14\66\1\330\16\66"+
    "\1\25\10\66\15\0\1\331\26\0\15\64\1\332\14\64"+
    "\1\25\11\64\15\66\1\333\15\66\1\25\10\66\4\25"+
    "\5\0\1\25\5\0\1\25\10\0\1\25\1\0\2\25"+
    "\1\0\1\25\2\0\4\25\4\334\5\64\1\334\5\64"+
    "\1\334\10\64\1\334\1\64\1\25\1\334\1\64\1\334"+
    "\2\64\4\334\4\335\5\66\1\335\5\66\1\335\10\66"+
    "\1\335\1\66\1\335\1\25\1\66\1\335\2\66\4\335";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7236];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\17\1\4\11\3\1\1\11\6\1\1\0\3\1"+
    "\2\0\1\1\1\0\2\1\1\0\1\1\3\0\2\1"+
    "\13\0\1\1\1\0\2\1\2\0\1\1\1\0\2\1"+
    "\1\0\1\1\3\0\2\1\11\0\2\1\2\0\1\1"+
    "\1\0\3\1\1\0\1\1\3\0\2\1\2\0\1\11"+
    "\6\0\2\1\2\0\1\1\1\0\2\1\1\0\1\1"+
    "\4\0\2\1\10\0\1\1\1\0\1\1\2\0\1\1"+
    "\1\0\2\1\1\0\1\1\4\0\2\1\3\0\1\11"+
    "\2\0\1\11\3\0\1\1\2\0\1\1\1\0\1\1"+
    "\3\0\3\1\2\0\1\11\1\0\1\11\2\0\1\1"+
    "\2\0\1\1\3\0\1\1\2\0\1\11\31\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[221];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	/** Variable used to store violation location and variable involved. **/
	String location = "MAIN PROGRAM";
	/** Variable used to store file value and function values associated. **/
	/** Boolean to determine if FILE is found. **/
	boolean fileFound = false;
	/** Boolean to determine if 'SCRATCH' is found. **/
	boolean scratchFound = false;
	/** Boolean to determine if STATUS is found. **/
	boolean statusFound = false;
	/** Boolean to determine if 'UNKNOWN' is found. **/
	boolean unknownFound = false;
	/** Boolean to determine if POSITION is found. **/
	boolean positionFound = false;
	/** Boolean to determine if IOSTAT is found. **/
	boolean iostatFound = false;
	/** Boolean to determine if the line is finished (there is no continuation mark). **/
	boolean endLine = true;
	
	public F90REFOpen() {
    }
	
	@Override
	public void setInputFile(IPath file) throws FileNotFoundException {
		super.setInputFile(file);
		this.zzReader = new FileReader(file.toOSString());
	}
	
	
	
	/**
	 * This method sent an error if a violation is found. There are 5 possible cases :
	 *    - IOSTAT is not found
	 *    - POSITION is not found
	 *    - STATUS is not found
	 *    - 'UNKNOWN' is used has a status
	 *    - FILE and 'SCRATCH' are missing (we can have a least one of them)
	 * @param fileFound
	 *			true if FILE is found, false otherwise
	 * @param scratchFound
	 *			true if 'SCRATCH' is found, false otherwise
	 * @param statusFound
	 *			true if STATUS is found, false otherwise
	 * @param unknownFound
	 *			true if 'UNKNOWN' is found, false otherwise
	 * @param positionFound
	 *			true if POSITION is found, false otherwise
	 * @param iostatFound
	 *			true if IOSTAT is found, false otherwise
	 **/
    public void checkViolation(final boolean fileFound,
            final boolean scratchFound, final boolean statusFound,
            final boolean unknownFound, final boolean positionFound,
            final boolean iostatFound) throws JFlexException {
        final boolean norFileNorScratch = !fileFound && !scratchFound;
        final boolean hasViolation =
                unknownFound || !positionFound || !statusFound || !iostatFound
                        || norFileNorScratch;
        if (hasViolation) {
            this.setError(this.location,"It misses one or more parameters in OPEN instruction. Mandato-ry parameters are FILE, STATUS, IOSTAT, POSITION.", this.yyline + 1);
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public F90REFOpen(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 192) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public List<Violation> run() throws java.io.IOException, JFlexException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { 	 
	return getViolations();
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            }
          case 16: break;
          case 2: 
            { yybegin(COMMENT);
            }
          case 17: break;
          case 3: 
            { throw new JFlexException( new Exception("Illegal character <" + yytext() + ">") );
            }
          case 18: break;
          case 4: 
            { yybegin(YYINITIAL);
            }
          case 19: break;
          case 5: 
            { location = location + " " + yytext(); 
							 yybegin(COMMENT);
            }
          case 20: break;
          case 6: 
            { if (endLine) {
										this.checkViolation(fileFound, scratchFound, statusFound, unknownFound, positionFound, iostatFound);
										fileFound = false;
										scratchFound = false;
										statusFound = false;
										unknownFound = false;
										positionFound = false;
										yybegin(YYINITIAL);
									 }
									 endLine = true;
            }
          case 21: break;
          case 7: 
            { endLine = false;
            }
          case 22: break;
          case 8: 
            { yybegin(OPEN);
            }
          case 23: break;
          case 9: 
            { fileFound = true;
            }
          case 24: break;
          case 10: 
            { location = yytext(); yybegin(NAMING);
            }
          case 25: break;
          case 11: 
            { iostatFound = true;
            }
          case 26: break;
          case 12: 
            { statusFound = true;
            }
          case 27: break;
          case 13: 
            { unknownFound = true;
            }
          case 28: break;
          case 14: 
            { scratchFound = true;
            }
          case 29: break;
          case 15: 
            { positionFound = true;
            }
          case 30: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
